/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Controller_FRM_Main;
/**
 *
 * @author JorgeIgnacio
 */
public class GUI_Product extends javax.swing.JPanel {

    Controller_FRM_Main controller_FRM_Main;
    /**
     * Creates new form GUI_Product
     */
    public GUI_Product() {
        initComponents();
    }
    
    public void addControllerButtons(Controller_FRM_Main controller_FRM_Main) {
        this.controller_FRM_Main = controller_FRM_Main;
        this.jB_Consult.addActionListener(controller_FRM_Main);
        this.jB_Save.addActionListener(controller_FRM_Main);
        this.jB_Close.addActionListener(controller_FRM_Main);
        this.jB_Add.addActionListener(controller_FRM_Main);
        this.jB_Modify.addActionListener(controller_FRM_Main);
        this.jB_Delete.addActionListener(controller_FRM_Main);
        this.jB_Update.addActionListener(controller_FRM_Main);
    }
    
    public void clean_jT() {
        this.jT_IdProduct.setText("");
        this.jT_Amount.setText("");
    }
    
    public String getIdProduct() {
        return this.jT_IdProduct.getText();
    }
    
    public void setInfo_jT(String arrayInfo[]) {
        this.jT_Amount.setText(arrayInfo[0]);
        this.jC_Description.setSelectedIndex(Integer.parseInt(arrayInfo[1]));
    }
    
    public String[] getInfo_jT() {
        String vectorInfo[] = new String[1];
        vectorInfo[0] = ""+this.jC_Description.getSelectedIndex();
        vectorInfo[1] = this.jT_Amount.getText();
        return vectorInfo;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Img = new javax.swing.JLabel();
        jL_IdProduct = new javax.swing.JLabel();
        jT_IdProduct = new javax.swing.JTextField();
        jB_Consult = new javax.swing.JButton();
        jL_Description = new javax.swing.JLabel();
        jC_Description = new javax.swing.JComboBox<>();
        jL_Amount = new javax.swing.JLabel();
        jT_Amount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Information = new javax.swing.JTextArea();
        jB_Save = new javax.swing.JButton();
        jB_Close = new javax.swing.JButton();
        jB_Add = new javax.swing.JButton();
        jB_Modify = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jB_Update = new javax.swing.JButton();

        jL_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/drawing.png"))); // NOI18N

        jL_IdProduct.setText("IDPRODUCT");

        jB_Consult.setText("CONSULT");

        jL_Description.setText("DESCRIPTION");

        jC_Description.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jL_Amount.setText("AMOUNT");

        jT_Information.setColumns(20);
        jT_Information.setRows(5);
        jScrollPane1.setViewportView(jT_Information);

        jB_Save.setText("SAVE");

        jB_Close.setText("CLOSE");

        jB_Add.setText("ADD");

        jB_Modify.setText("MODIFY");

        jB_Delete.setText("DELETE");

        jB_Update.setText("UPDATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL_Amount)
                                    .addComponent(jL_IdProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT_IdProduct)
                                    .addComponent(jC_Description, 0, 76, Short.MAX_VALUE)
                                    .addComponent(jT_Amount))
                                .addGap(18, 18, 18)
                                .addComponent(jB_Consult)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Save)
                    .addComponent(jB_Close))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_IdProduct)
                            .addComponent(jT_IdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Consult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Description)
                            .addComponent(jC_Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Amount)
                            .addComponent(jT_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Add)
                    .addComponent(jB_Modify)
                    .addComponent(jB_Delete)
                    .addComponent(jB_Update))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Add;
    private javax.swing.JButton jB_Close;
    private javax.swing.JButton jB_Consult;
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_Modify;
    private javax.swing.JButton jB_Save;
    private javax.swing.JButton jB_Update;
    private javax.swing.JComboBox<String> jC_Description;
    private javax.swing.JLabel jL_Amount;
    private javax.swing.JLabel jL_Description;
    private javax.swing.JLabel jL_IdProduct;
    private javax.swing.JLabel jL_Img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Amount;
    private javax.swing.JTextField jT_IdProduct;
    private javax.swing.JTextArea jT_Information;
    // End of variables declaration//GEN-END:variables
}
